/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ub.prog2.DempereGuillermoGerman.vista;

import edu.ub.prog2.DempereGuillermoGerman.controlador.CtrlVisor;
import edu.ub.prog2.DempereGuillermoGerman.model.Imatge;
import edu.ub.prog2.utils.ImageList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Akira
 */
public class FrmAfegirImatge extends javax.swing.JFrame {

    private ImageList imageList;
    private CtrlVisor ctrl;

    /**
     * Creates new form FrmAfegirImatge
     */
    public FrmAfegirImatge(ImageList list, CtrlVisor ctrl) {
        this.imageList = list;
        this.ctrl = ctrl;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFilePath = new javax.swing.JTextField();
        jBrowseFilesButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jFileTitle = new javax.swing.JTextField();
        jAddImage = new javax.swing.JButton();
        jCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Afegir nova Imatge");
        setName("jAddImageFrame"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jFilePath.setEditable(false);
        jFilePath.setText("C:/Imatges/...");
        getContentPane().add(jFilePath, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 290, -1));

        jBrowseFilesButton.setText("Examinar");
        jBrowseFilesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBrowseFilesButtonActionPerformed(evt);
            }
        });
        getContentPane().add(jBrowseFilesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 90, 20));

        jLabel1.setText("Titol de la Imatge:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 20));
        getContentPane().add(jFileTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 180, -1));

        jAddImage.setText("Afegir");
        jAddImage.setEnabled(false);
        jAddImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddImageActionPerformed(evt);
            }
        });
        getContentPane().add(jAddImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));

        jCancel.setText("Cancelar");
        jCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelActionPerformed(evt);
            }
        });
        getContentPane().add(jCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, -1));

        setSize(new java.awt.Dimension(419, 136));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBrowseFilesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBrowseFilesButtonActionPerformed
        JFileChooser fc = new JFileChooser(".");
        fc.showDialog(this, null);
        jFilePath.setText(fc.getSelectedFile().getAbsolutePath());
        jAddImage.setEnabled(true);
    }//GEN-LAST:event_jBrowseFilesButtonActionPerformed

    private void jCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jCancelActionPerformed

    private void jAddImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddImageActionPerformed
        if (ctrl.addImageToList(jFileTitle.getText(), jFilePath.getText(), imageList)) {
            JOptionPane.showMessageDialog(this, "Imatge afegida correctament.");
        } else {
            JOptionPane.showMessageDialog(
                    this, "Error afegint la nova clase.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        //this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jAddImageActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAddImage;
    private javax.swing.JButton jBrowseFilesButton;
    private javax.swing.JButton jCancel;
    private javax.swing.JTextField jFilePath;
    private javax.swing.JTextField jFileTitle;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
