/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ub.prog2.DempereGuillermoGerman.vista.forms;

import edu.ub.prog2.DempereGuillermoGerman.controlador.CtrlVisor;
import edu.ub.prog2.DempereGuillermoGerman.model.Imatge;
import edu.ub.prog2.utils.ImageList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Akira
 */
public class FormAddImageToLib extends javax.swing.JFrame {

    private ImageList lib;
    private CtrlVisor ctrl;

    /**
     * Creates new form FrmAfegirImatge
     */
    public FormAddImageToLib(CtrlVisor ctrl) {
	this.lib = ctrl.getData().getLib();
	this.ctrl = ctrl;
	initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFilePath = new javax.swing.JTextField();
        jBrowseFilesButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jFileTitle = new javax.swing.JTextField();
        jAddImage = new javax.swing.JButton();
        jCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Afegir nova Imatge a la Biblioteca");
        setName("jAddImageFrame"); // NOI18N
        setResizable(false);

        jFilePath.setEditable(false);
        jFilePath.setText("C:/Imatges/...");

        jBrowseFilesButton.setText("Examinar");
        jBrowseFilesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBrowseFilesButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Titol de la Imatge:");

        jFileTitle.setNextFocusableComponent(jAddImage);

        jAddImage.setText("Afegir");
        jAddImage.setEnabled(false);
        jAddImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddImageActionPerformed(evt);
            }
        });

        jCancel.setText("Cancelar");
        jCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBrowseFilesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jAddImage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCancel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jFileTitle)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBrowseFilesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFileTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAddImage)
                    .addComponent(jCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(361, 145));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBrowseFilesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBrowseFilesButtonActionPerformed
	JFileChooser fc = new JFileChooser(".");
	// If file is chosen
	if (fc.showDialog(this, null) == JFileChooser.APPROVE_OPTION) {
	    jFilePath.setText(fc.getSelectedFile().getAbsolutePath());
	    jAddImage.setEnabled(true);
	}
    }//GEN-LAST:event_jBrowseFilesButtonActionPerformed

    private void jCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelActionPerformed
	this.dispose();
    }//GEN-LAST:event_jCancelActionPerformed

    private void jAddImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddImageActionPerformed
	if (ctrl.addImageToList(jFileTitle.getText(), jFilePath.getText(), lib)) {
	    //JOptionPane.showMessageDialog(this, "Imatge afegida correctament.");
	} else {
	    JOptionPane.showMessageDialog(
		    this, "Error afegint la nova clase.", "Error", JOptionPane.ERROR_MESSAGE);
	}
	//this.setVisible(false);
	this.dispose();
    }//GEN-LAST:event_jAddImageActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAddImage;
    private javax.swing.JButton jBrowseFilesButton;
    private javax.swing.JButton jCancel;
    private javax.swing.JTextField jFilePath;
    private javax.swing.JTextField jFileTitle;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
