/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ub.prog2.DempereGuillermoGerman.vista.forms;

import edu.ub.prog2.DempereGuillermoGerman.model.AlbumImatges;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author Akira
 */
public class FormEditAlbum extends javax.swing.JFrame {

    //private CtrlVisor ctrl;
    private AlbumImatges album;

    /**
     * Creates new form FrmAfegirImatge
     */
    public FormEditAlbum(AlbumImatges album) {
	initComponents();

	this.album = album;

	// Set title
	jTextTitle.setText(album.getTitle());
	jTextAuthor.setText(album.getAuthor());

	jSliderCap.setValue(album.getCap());
	jNumberCap.setText(album.getCap()+"");

	// Slider change listener
	jSliderCap.addChangeListener(new ChangeListener() {
	    @Override
	    public void stateChanged(ChangeEvent e) {
		jNumberCap.setText(jSliderCap.getValue() + "");
	    }
	});

    }

    /**
     *
     *
     * /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jImageFiltersGroup = new javax.swing.ButtonGroup();
        jLabelTitle = new javax.swing.JLabel();
        jTextTitle = new javax.swing.JTextField();
        jAccept = new javax.swing.JButton();
        jCancel = new javax.swing.JButton();
        jLabelTitle1 = new javax.swing.JLabel();
        jTextAuthor = new javax.swing.JTextField();
        jLabelTitle2 = new javax.swing.JLabel();
        jSliderCap = new javax.swing.JSlider();
        jNumberCap = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editar Imatge");
        setName("jAddImageFrame"); // NOI18N
        setResizable(false);

        jLabelTitle.setText("Titol del Album:");

        jTextTitle.setNextFocusableComponent(jTextAuthor);

        jAccept.setText("Acceptar");
        jAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAcceptActionPerformed(evt);
            }
        });

        jCancel.setText("Cancelar");
        jCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelActionPerformed(evt);
            }
        });

        jLabelTitle1.setText("Autor del Album:");

        jLabelTitle2.setText("Limit d'Imatges:");

        jSliderCap.setMajorTickSpacing(50);
        jSliderCap.setMinorTickSpacing(10);
        jSliderCap.setPaintTicks(true);
        jSliderCap.setSnapToTicks(true);
        jSliderCap.setValue(10);

        jNumberCap.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jNumberCap.setText("-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jAccept)
                            .addComponent(jLabelTitle2))
                        .addGap(32, 32, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jCancel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSliderCap, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jNumberCap, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelTitle1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabelTitle)
                                .addGap(34, 34, 34)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextTitle)
                            .addComponent(jTextAuthor, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextAuthor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTitle2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSliderCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNumberCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCancel)
                    .addComponent(jAccept))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(270, 184));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelActionPerformed
	this.dispose();
    }//GEN-LAST:event_jCancelActionPerformed

    private void jAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAcceptActionPerformed
	album.setTitle(jTextTitle.getText());
	album.setAuthor(jTextAuthor.getText());
	album.setCap(jSliderCap.getValue());

	this.dispose();
    }//GEN-LAST:event_jAcceptActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAccept;
    private javax.swing.JButton jCancel;
    private javax.swing.ButtonGroup jImageFiltersGroup;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelTitle1;
    private javax.swing.JLabel jLabelTitle2;
    private javax.swing.JTextField jNumberCap;
    private javax.swing.JSlider jSliderCap;
    private javax.swing.JTextField jTextAuthor;
    private javax.swing.JTextField jTextTitle;
    // End of variables declaration//GEN-END:variables
}
