/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ub.prog2.DempereGuillermoGerman.vista.forms;

import edu.ub.prog2.DempereGuillermoGerman.controlador.CtrlVisor;
import edu.ub.prog2.utils.ImageFile;
import edu.ub.prog2.utils.ImageList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Akira
 */
public class FormAddImageToAlbum extends javax.swing.JFrame {

    private final ImageList album;
    private final ImageList lib;
    private final CtrlVisor ctrl;

    /**
     * Creates new form FrmAfegirImatge
     */
    public FormAddImageToAlbum(ImageList list, CtrlVisor ctrl) {
        this.album = list;
        this.ctrl = ctrl;
        this.lib = ctrl.getData().getLib();
        initComponents();
        
        jLibImageList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        addImgsToList();
    }
    
    private void addImgsToList(){
        // Refresh the image list
        DefaultListModel dlm = new DefaultListModel();
        for (ImageFile img : lib.getList()) {
            dlm.addElement(img.toString());
        }
        jLibImageList.setModel(dlm);

        ListSelectionModel lsm = jLibImageList.getSelectionModel();
        lsm.addListSelectionListener(new ListSelectionListener(){
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if(e.getValueIsAdjusting()) return;
                jAddImage.setEnabled(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jAddImage = new javax.swing.JButton();
        jCancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLibImageList = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Afegir nova Imatge al Album");
        setMinimumSize(new java.awt.Dimension(200, 200));
        setName("jAddImageFrame"); // NOI18N

        jAddImage.setText("Afegir");
        jAddImage.setEnabled(false);
        jAddImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddImageActionPerformed(evt);
            }
        });

        jCancel.setText("Cancelar");
        jCancel.setMaximumSize(null);
        jCancel.setMinimumSize(new java.awt.Dimension(180, 210));
        jCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelActionPerformed(evt);
            }
        });

        jLibImageList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jLibImageList.setMaximumSize(null);
        jLibImageList.setMinimumSize(null);
        jScrollPane1.setViewportView(jLibImageList);

        jLabel2.setText("Imatges a la Biblioteca:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jAddImage)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                                .addComponent(jCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAddImage)
                    .addComponent(jCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(236, 218));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jCancelActionPerformed

    private void jAddImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddImageActionPerformed
        int index = jLibImageList.getSelectedIndex();

        try {
            ImageFile img = lib.getAt(index);
            album.addImage(img);
            //JOptionPane.showMessageDialog(this, "Imatge afegida correctament.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                this, "Error Afegint la imatge: " + e.getMessage() + ".", "Error", JOptionPane.ERROR_MESSAGE);
        }

        //this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jAddImageActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAddImage;
    private javax.swing.JButton jCancel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList jLibImageList;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
